#Database Configuration - Active DB: H2
#Sun Oct 05 22:37:55 COT 2025
oracle.url=jdbc\:oracle\:thin\:@localhost\:1521/XEPDB1
oracle.user=universidad_user
oracle.password=universidad_pass
db.password=
h2.url=jdbc\:h2\:mem\:universidad;DB_CLOSE_DELAY\=-1
h2.password=
mysql.password=universidad_pass
h2.driver=org.h2.Driver
db.driver=org.h2.Driver
oracle.driver=oracle.jdbc.OracleDriver
db.user=sa
h2.user=sa
mysql.user=universidad_user
mysql.url=jdbc\:mysql\://localhost\:3306/sistema_universitario?useSSL\=false&allowPublicKeyRetrieval\=true
mysql.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc\:h2\:mem\:universidad;DB_CLOSE_DELAY\=-1
